package My_Forms;

import My_Classes.Centre;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andreea
 */
public class AddCentreForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGenresForm
     */
    
    //create a member object
    My_Classes.Centre centru = new My_Classes.Centre();
    
    //crate a variable to store the profile picture path
    String imagePath = null;
    
    public AddCentreForm() {
        initComponents();
        
        this.setLocationRelativeTo(null); //center
        
        //add gray border
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3,3,3,3, new Color(1, 152, 117));
        jPanel1.setBorder(panelHeaderBorder);
        
        //dispaly image
        My_Classes.Func_Class func = new My_Classes.Func_Class();
        func.displayImage(90, 60, null, "/My_images/members.png", jLabel1_FormTitle);
        
        jLabel_EmptyName_.setVisible(false);
        jLabel_EmptyCity_.setVisible(false);
        jLabel_EmptyStreet_.setVisible(false);
        jLabel_EmptyCounty_.setVisible(false);
        jLabel_EmptyNumber_.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jButton_Add_ = new javax.swing.JButton();
        jLabel_EmptyStreet_ = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1_FormTitle = new javax.swing.JLabel();
        jTextField_Judet = new javax.swing.JTextField();
        jLabel_EmptyName_ = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Localitate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel_EmptyCity_ = new javax.swing.JLabel();
        jLabel_CNP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Strada = new javax.swing.JTextField();
        jTextField_Numar = new javax.swing.JTextField();
        jLabel_EmptyCounty_ = new javax.swing.JLabel();
        jLabel_EmptyNumber_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel_CloseForm.setBackground(new java.awt.Color(1, 152, 117));
        jLabel_CloseForm.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 14)); // NOI18N
        jLabel1.setText("Nume:");

        jTextField_Name.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jButton_Add_.setText("Adauga centru");
        jButton_Add_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ActionPerformed(evt);
            }
        });

        jLabel_EmptyStreet_.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel_EmptyStreet_.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_EmptyStreet_.setText("*introduceti strada");
        jLabel_EmptyStreet_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyStreet_MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(1, 152, 117));

        jLabel1_FormTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1_FormTitle.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_FormTitle.setText("Adaugare Centru");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_Judet.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField_Judet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_JudetActionPerformed(evt);
            }
        });

        jLabel_EmptyName_.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel_EmptyName_.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_EmptyName_.setText("*introduceti numele");
        jLabel_EmptyName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyName_MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans CJK TC", 1, 14)); // NOI18N
        jLabel4.setText("Localitate:");

        jTextField_Localitate.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField_Localitate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LocalitateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 14)); // NOI18N
        jLabel5.setText("Numar:");

        jLabel_EmptyCity_.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel_EmptyCity_.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_EmptyCity_.setText("*introduceti localitatea");
        jLabel_EmptyCity_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyCity_MouseClicked(evt);
            }
        });

        jLabel_CNP.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 14)); // NOI18N
        jLabel_CNP.setText("Judet:");

        jLabel7.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 14)); // NOI18N
        jLabel7.setText("Strada:");

        jTextField_Strada.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField_Strada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_StradaActionPerformed(evt);
            }
        });

        jTextField_Numar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField_Numar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumarActionPerformed(evt);
            }
        });

        jLabel_EmptyCounty_.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel_EmptyCounty_.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_EmptyCounty_.setText("*introduceti judetul");
        jLabel_EmptyCounty_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyCounty_MouseClicked(evt);
            }
        });

        jLabel_EmptyNumber_.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel_EmptyNumber_.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_EmptyNumber_.setText("*introduceti numarul");
        jLabel_EmptyNumber_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyNumber_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Name)
                    .addComponent(jTextField_Localitate)
                    .addComponent(jTextField_Judet)
                    .addComponent(jButton_Add_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Numar)
                    .addComponent(jTextField_Strada)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_EmptyName_, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel_EmptyCity_, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_CNP)
                            .addComponent(jLabel_EmptyStreet_, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EmptyCounty_, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel_EmptyNumber_, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EmptyName_, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Localitate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EmptyCity_, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CNP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Judet, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EmptyCounty_, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTextField_Strada, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EmptyStreet_, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Numar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_EmptyNumber_, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jButton_Add_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        // TODO add your handling code here:
        
        //close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jButton_Add_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ActionPerformed
        
        //hide the jlabel "empty message"
        jLabel_EmptyName_.setVisible(false);
        jLabel_EmptyCity_.setVisible(false);
        jLabel_EmptyCounty_.setVisible(false);
        jLabel_EmptyNumber_.setVisible(false);
        jLabel_EmptyStreet_.setVisible(false);
        
        //get the member data
        String name = jTextField_Name.getText();
        String city = jTextField_Localitate.getText();
        //String phone = jTextField_CNP.getText();
        String street = jTextField_Strada.getText();
        String county = jTextField_Judet.getText();
        String number = jTextField_Numar.getText();

        //check if the textfield is empty
        if (name.isEmpty())
        {
            jLabel_EmptyName_.setVisible(true);
        } 
        else if (city.isEmpty())
        {
            jLabel_EmptyCity_.setVisible(true);
        }
        else if (street.isEmpty())
        {
            jLabel_EmptyStreet_.setVisible(true);
        }
        
        else if (county.isEmpty())
        {
            jLabel_EmptyCounty_.setVisible(true);
        }
        
        else if (number.isEmpty())
        {
            jLabel_EmptyNumber_.setVisible(true);
        }
        /*else
        {
            byte [] img = null;
            
            if(imagePath != null)
            {
                
                try {
                    
                    Path path = Paths.get(imagePath);
                    img = Files.readAllBytes(path);
                    member.addMember(fname, lname, phone, email, gender, img);
                    
                } catch (IOException ex) {
                    Logger.getLogger(AddMemberForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }else
            {
                JOptionPane.showMessageDialog(null, "Select a Profile Pic For This Member", "No Picture Selected", 2);
            }
                      
        }*/
        centru.addCentru(name, city, county, street, number); 
        
        

    }//GEN-LAST:event_jButton_Add_ActionPerformed
    
    
    private void jLabel_EmptyStreet_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyStreet_MouseClicked
        
        // hide this jlabel on click
        jLabel_EmptyStreet_.setVisible(false);
        
    }//GEN-LAST:event_jLabel_EmptyStreet_MouseClicked

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_JudetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_JudetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JudetActionPerformed

    private void jLabel_EmptyName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyName_MouseClicked
        // TODO add your handling code here:
        // hide this jlabel on click
        jLabel_EmptyName_.setVisible(false);
    }//GEN-LAST:event_jLabel_EmptyName_MouseClicked

    private void jTextField_LocalitateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LocalitateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LocalitateActionPerformed

    private void jLabel_EmptyCity_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyCity_MouseClicked
        // TODO add your handling code here:
        // hide this jlabel on click
        jLabel_EmptyCity_.setVisible(false);
    }//GEN-LAST:event_jLabel_EmptyCity_MouseClicked

    private void jTextField_StradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_StradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_StradaActionPerformed

    private void jTextField_NumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumarActionPerformed

    private void jLabel_EmptyCounty_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyCounty_MouseClicked
        // TODO add your handling code here:
        jLabel_EmptyCounty_.setVisible(false);
    }//GEN-LAST:event_jLabel_EmptyCounty_MouseClicked

    private void jLabel_EmptyNumber_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyNumber_MouseClicked
        // TODO add your handling code here:
        jLabel_EmptyNumber_.setVisible(false);
    }//GEN-LAST:event_jLabel_EmptyNumber_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCentreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_FormTitle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_CNP;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_EmptyCity_;
    private javax.swing.JLabel jLabel_EmptyCounty_;
    private javax.swing.JLabel jLabel_EmptyName_;
    private javax.swing.JLabel jLabel_EmptyNumber_;
    private javax.swing.JLabel jLabel_EmptyStreet_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_Judet;
    private javax.swing.JTextField jTextField_Localitate;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Numar;
    private javax.swing.JTextField jTextField_Strada;
    // End of variables declaration//GEN-END:variables
}
